### ISSUE TITLE
test `push_front_slice_ring_buffer` fails on i386 with default features and `--no-default-features`

### ISSUE THREAD

**Issue by dkg** [LiquidityC/slice_ring_buffer#11]
On [Debian CI infrastructure, on i386](https://ci.debian.net/packages/r/rust-slice-ring-buffer/unstable/i386/52480587/), running `cargo test --no-default-features`   and `cargo test` both have the `push_front_slice_ring_buffer` failing, with the same backtrace:

```
155s test push_front_slice_ring_buffer ... FAILED
155s 
155s failures:
155s 
155s ---- push_front_slice_ring_buffer stdout ----
155s thread 'push_front_slice_ring_buffer' panicked at /usr/share/cargo/registry/slice-ring-buffer-0.3.4/src/lib.rs:413:17:
155s "ut-of-memoryocate a buffer with capacity "stack backtrace:
155s    0: rust_begin_unwind
155s              at /usr/src/rustc-1.80.1/library/std/src/panicking.rs:652:5
155s    1: core::panicking::panic_fmt
155s              at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:72:14
155s    2: core::panicking::panic_display
155s              at /usr/src/rustc-1.80.1/library/core/src/panicking.rs:262:5
155s    3: slice_ring_buffer::SliceRingBuffer<T>::with_capacity::{{closure}}
155s              at ./src/lib.rs:413:17
155s    4: core::result::Result<T,E>::unwrap_or_else
155s              at /usr/src/rustc-1.80.1/library/core/src/result.rs:1456:23
155s    5: slice_ring_buffer::SliceRingBuffer<T>::with_capacity
155s              at ./src/lib.rs:408:23
155s    6: push_front::push_front_slice_ring_buffer
155s              at ./benches/push_front.rs:22:9
155s    7: push_front::push_front_slice_ring_buffer::{{closure}}
155s              at ./benches/push_front.rs:20:55
155s    8: core::ops::function::FnOnce::call_once
155s              at /usr/src/rustc-1.80.1/library/core/src/ops/function.rs:250:5
155s    9: test::types::RunnableTest::run::{{closure}}::{{closure}}
155s              at /usr/src/rustc-1.80.1/library/test/src/types.rs:149:76
155s note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
155s 
155s 
155s failures:
155s     push_front_slice_ring_buffer
155s 
```

These failures [do not seem to happen on non-i386 platforms](https://ci.debian.net/packages/r/rust-slice-ring-buffer/).

**Comment by dkg** [comment]
it looks to me like `benches/push_front.rs` assumes that a billion iterations will fit in RAM:

```
const MAX_NO_ITERS: usize = 1_000_000_000;
```

It's not clear to me why `push_front_slice_ring_buffer` fails under the default feature set (which includes `use_std`), but succeeds when running `cargo test --features use_std`.   It's also not clear to me how this succeeds on other 32-bit architectures, but not in i386!

In debian, we're even [reducing the size of these slices for testing](https://salsa.debian.org/rust-team/debcargo-conf/-/blob/master/src/slice-ring-buffer/debian/patches/reduce-benches.patch?ref_type=heads) in the hopes that this will let the builds proceed.
